### ISSUE TITLE
Shimmer effect grows wider when its height is big

### ISSUE THREAD

**Issue by tasomaniac** [team-supercharge/ShimmerLayout#24]
I'm not sure what is wrong exactly but I have some weird behavior when I try to use the library with a complex and full-screen layout. 

We are actually using the library for another screen where we only have small list item. That works fine. 

Here is how it looks like. The shimmer is wider on the bottom. 

![shimmer](https://user-images.githubusercontent.com/763339/30552525-8374f5c0-9c9e-11e7-9cca-ed023320846e.gif)

**Comment by veghtomi** [comment]
@tasomaniac This is not an issue and the height has nothing to do with it. The problem (or I would not say it is a problem) is that your are using different background colors for the views in the animation. The color of the shimmer line has a zero alpha value at the left and right side and 1 alpha value at the middle. This means if you have a lighter color than the shimmer line, the line will look wider since the edges will be visible even when they only have 0.1 alpha. On the other hand, when you use darker colors the situation is quite the opposite. The edges of the shimmer line will be visible if they have higher alpha value  so only the part near to the vertical center of the line will be visible. 

So by using the same background your issue will be fixed.

I suggest reading the [article](https://medium.com/supercharges-mobile-product-guide/shimmerlayout-26978ab53c28) listed in the README section, it will help a lot! :)

**Comment by tasomaniac** [comment]
We saw the article and wanted to switch from the other library.
In our case, it is actually not possible to change the colors. We may change the colors of call and email buttons but the image below the buttons even has a lot of transparency.

So you're saying that this is the limitation of the library and it is not possible to do shimmer on an arbitrary image? So it needs to have a single color for the library to work?

**Comment by veghtomi** [comment]
So basically yes, using one color is the easiest way but for different backgrounds it looks slightly different. What you can do is to play with the background alpha, so when you decrease the alpha of the top view, the line will be wider, but the line below the buttons will not change.

As for images, it can run on any image.
